---
title: "education_race_eda"
format: pdf
---

```{r}
library(tidyverse)
library(arrow)
library(ggthemes)
library(patchwork)

data <- read_parquet("../data/clean_data.parquet")
```

```{r}
glimpse(data[1:27])
```

```{r}
education_eda_18 <- data %>% 
  dplyr::filter(age > 18,
         esr != "Not in Labor Force"
         ) %>% 
  dplyr::select(age,
         race,
         race_simp,
         gross_rent,
         income_personal,
         education,
         health_insurance,
         snap_benefits,
         puma)
```

```{r}
edu_inc_plot <- education_eda_18 %>%
  filter(income_personal <= 500000) %>% 
  ggplot() +
    geom_boxplot(aes(x = income_personal / 1000,
                     y = reorder(education, income_personal)),
                 outlier.shape = NA) + 
  theme_few() +
  ylab("") +
  xlab("Income (Thousands)") +
  labs(
    title = "Plot 1: Higher Education Level Is Associated with Higher Income",
       #caption = "Source: ACS PUMS 2024 for LA County"
       ) +
  theme(plot.title = element_text(hjust = 0.5))

edu_inc_plot

ggsave("../../statistical_report/edu_inc_plot.png",
       edu_inc_plot,
       width = 10, 
       height = 6, 
       dpi = 600)
```

```{r}
race_edu_plot <- education_eda_18 %>% 
  mutate(race_simp = factor(race_simp,
                            levels = c("White", "Hispanic", "Asian", "Black", "Other")),
         education = factor(education,
                            levels = c("Post-bacc professional degree",
                                       "Doctorate degree",
                                       "Master's degree",
                                       "Bachelor's degree",
                                       "Associate's degree",
                                       "Some college",
                                       "Regular high school diploma",
                                       "GED or alternative credential",
                                       "Less than High School",
                                       "No schooling completed"))) %>% 
  ggplot() +
    geom_bar(aes(y = education,
                 fill = race_simp),
             position = position_fill(reverse = TRUE)) +
  scale_fill_manual(values = c("Asian" = "#e41a1c",
                               "White" = "#377eb8",
                               "Hispanic" = "#4daf4a",
                               "Black" = "#984ea3", 
                               "Other" = "#ff7f00")) +
  scale_y_discrete(limits = rev) + 
  theme_few() +
  xlab("")+
  ylab("") +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  labs(fill = "",
       title = "Plot 2: Race Is Disproportionately Spread Across Education Levels",
       #caption = "Source: ACS PUMS 2024 for LA County"
       )

race_edu_plot

ggsave("../../statistical_report//race_edu_plot.png",
       race_edu_plot,
       width = 10, 
       height = 6, 
       dpi = 600)
```

```{r}
inc_race_plot <-education_eda_18 %>% 
  mutate(race_simp = factor(race_simp,
                            levels = c("White", "Hispanic", "Asian", "Black", "Other")),
         education = factor(education,
                            levels = c("Post-bacc professional degree",
                                       "Doctorate degree",
                                       "Master's degree",
                                       "Bachelor's degree",
                                       "Associate's degree",
                                       "Some college",
                                       "Regular high school diploma",
                                       "GED or alternative credential",
                                       "Less than High School",
                                       "No schooling completed"))) %>% 
  mutate(income_brackets = case_when(income_personal <= 15000 ~ "0-15k",
                                     income_personal <= 30000 ~ "15k-30k",
                                     income_personal <= 60000 ~ "30k-60k",
                                     income_personal <= 90000 ~ "60k-90k",
                                     income_personal <= 120000 ~ "90k-120k",
                                     income_personal <= 150000 ~ "120k-150k",
                                     income_personal > 150000 ~ "150k+")) %>% 
  dplyr::select(race_simp, income_brackets, income_personal) %>%
  ggplot() +
    geom_bar(aes(y = reorder(income_brackets,income_personal),
                 fill = race_simp),
             position = position_fill(reverse = TRUE)) +
    scale_fill_manual(values = c("Asian" = "#e41a1c",
                               "White" = "#377eb8",
                               "Hispanic" = "#4daf4a",
                               "Black" = "#984ea3", 
                               "Other" = "#ff7f00")) +
    theme_few() +
    theme(axis.text.x = element_blank(),
         axis.ticks.x = element_blank()) +
    labs(fill = "",
         title = "Plot 3: Race Is Disproportionately Spread Across Income Brackets",
        #caption = "Source: ACS PUMS 2024 for LA County"
        ) +
    xlab("")+
    ylab("")

inc_race_plot

ggsave("../../statistical_report/inc_race_plot.png",
       inc_race_plot,
       width = 10, 
       height = 6, 
       dpi = 600)
```

```{r}
inc_race_plot / race_edu_plot + plot_annotation(caption = "Figure")
```

