---
title: "logistic_cit"
format: pdf
---

```{r include=FALSE}
library(tidyverse)
library(arrow)
library(purrr)
library(survey)
library(srvyr)
library(broom)
library(gt)
library(ggthemes)
library(patchwork)

data <- read_parquet("../data/clean_data.parquet")
```

```{r echo=FALSE}
model_inputs <- data %>% 
  dplyr::filter(age > 18,
         esr != "Not in Labor Force"
         ) %>% 
  dplyr::mutate(
         # Merge no schooling into less than high school before factoring
         education = case_when(
           education == "No schooling completed" ~ "Less than High School",
           TRUE ~ education
         ),
         cit_simp = ifelse(cit != "Not a U.S. citizen",
                                 "Citizen",
                                 "Non-Citizen"),
         cit_simp = factor(cit_simp,
                           levels = c("Citizen",
                                            "Non-Citizen")),
         education = factor(education,
                       levels = c("Post-bacc professional degree",
                                  "Doctorate degree",
                                  "Master's degree",
                                  "Bachelor's degree",
                                  "Associate's degree",
                                  "Some college",
                                  "Regular high school diploma",
                                  "GED or alternative credential",
                                  "Less than High School"))) %>% 
  select(race_simp, cit_simp, education, pwgtp, pwgtp1:pwgtp80)
```

```{r}
model_inputs %>%
  filter(cit_simp == "Citizen",
         race_simp != "Hispanic") %>% 
  summarise(
    education = names(sort(table(education), decreasing = TRUE))[1],
    race_simp = names(sort(table(race_simp), decreasing = TRUE))[1]
  )
```

# The full logistic design

```{r}
logist_reg_design <- model_inputs %>% 
  mutate(
    cit_binary = as.numeric(cit_simp == "Non-Citizen"),  # 1 = Non-Citizen, 0 = Citizen
    education  = relevel(factor(education), ref = "Bachelor's degree"),
    race_simp  = relevel(factor(race_simp), ref = "White")
  ) %>%
  as_survey_rep(
    weights    = pwgtp,
    repweights = all_of(rep_weights),
    type       = "successive-difference",
    mse        = TRUE
  )
```

```{r}
log_reg <- logist_reg_design %>%
  svyglm(
    formula   = cit_binary ~ education + race_simp + education:race_simp,
    design    = .,
    family    = binomial(link = "logit"),
    na.action = na.omit
  )

log_reg_back <- step(log_reg, direction = "backward")

summary(log_reg_back)
```

```{r}
log_full_table <- tidy(log_reg_back, conf.int = TRUE) %>%
  filter(p.value < 0.05, term != "(Intercept)") %>%
  mutate(
    term           = str_remove_all(term, "education|race_simp|cit_simp"),
    odds_ratio     = round(exp(estimate), 3),
    percent_change = round((exp(estimate) - 1) * 100, 1),
    conf_low       = round(exp(conf.low), 3),
    conf_high      = round(exp(conf.high), 3),
    p.value        = ifelse(p.value < 0.001, "< .001", round(p.value, 3))
  ) %>%
  dplyr::select(term, odds_ratio, percent_change, conf_low, conf_high, statistic, p.value) %>%
  arrange(desc(percent_change)) %>% 
  gt() %>%
  tab_header(title = "Table S3: Full Results for Logistic Regression") %>% 
  cols_label(
    term           = "Term",
    percent_change = "% Change in Odds",
    odds_ratio     = "Odds Ratio",
    conf_low       = "95% CI Low",
    conf_high      = "95% CI High",
    statistic      = "t",
    p.value        = "p"
  ) %>%
  tab_source_note("Reference: Bachelor's degree, white ")

log_full_table

gtsave(log_full_table,
       "../../statistical_report/log_full_table.png")
```

```{r}
sig_odds <- tidy(log_reg_back, conf.int = TRUE) %>%
  filter(p.value < 0.05, term != "(Intercept)") %>%
  mutate(
    term           = str_remove_all(term, "education|race_simp|cit_simp"),
    odds_ratio     = round(exp(estimate), 3),
    percent_change = round((exp(estimate) - 1) * 100, 1),
    conf_low       = round(exp(conf.low), 3),
    conf_high      = round(exp(conf.high), 3),
    p.value        = ifelse(p.value < 0.001, "< .001", round(p.value, 3))
  ) %>%
  dplyr::select(term, odds_ratio, percent_change, conf_low, conf_high, statistic, p.value)

make_odds_gt <- function(data, title) {
  data %>%
    gt() %>%
    cols_label(
      term           = "Term",
      odds_ratio     = "Odds Ratio",
      percent_change = "% Change in Odds",
      conf_low       = "95% CI Low",
      conf_high      = "95% CI High",
      statistic      = "t",
      p.value        = "p"
    ) %>%
    tab_header(title = title) %>%
    tab_source_note("Reference: Bachelor's degree, white ")
}

# Top 5 increases
log_5_increase <- sig_odds %>%
  arrange(desc(percent_change)) %>%
  slice_head(n = 5) %>%
  make_odds_gt("Table 16: Top 5 Largest Increases in Odds of Being Non-Citizen")

# Top 5 decreases
log_5_decrease <- sig_odds %>%
  arrange(percent_change) %>%
  slice_head(n = 5) %>%
  make_odds_gt("Table 17: Top 5 Largest Decreases in Odds of Being Non-Citizen")

gtsave(log_5_increase,
       "../../statistical_report/log_5_increase.png")
gtsave(log_5_decrease,
       "../../statistical_report/log_5_decrease.png")
```

