---
title: "Untitled"
format: pdf
---

```{r}
############################
# 0) Libraries + Load Data
############################
library(tidyverse)
library(arrow)

# Additional packages used below:
# install.packages(c("rcompanion", "MASS", "glmnet"))  # if needed
library(rcompanion)  # pairwise nominal independence tests
library(MASS)        # stepAIC
library(glmnet)      # lasso


library(ggthemes)
library(survey)
library(srvyr)
library(broom)
library(gt)
library(prettyunits)

data <- read_parquet("../data/clean_data.parquet")

#Apply the weights, per the PUMS User Guide
data_selected <- data %>% 
  mutate(cit_simp = ifelse(cit != "Not a U.S. citizen",
                                 "Citizen",
                                 "Non-Citizen"),
         cit_simp = factor(cit_simp,
                           levels = c("Non-Citizen",
                                            "Citizen"))) %>% 
  select(income_personal, age, race_simp, cit_simp, gross_rent, education, health_insurance,
          snap_benefits, jwtrns, puma, pwgtp, pwgtp1:pwgtp80)

rep_weights <- paste0("pwgtp", 1:80)

acs_design <- data_selected %>%
  as_survey_rep(
    weights    = pwgtp,
    repweights = all_of(rep_weights),
    type       = "successive-difference",
    mse        = TRUE
  )
```

```{r}
############################
# 1) Setup Variables
############################

# Restrict to adults 
data_selected <- data_selected %>% filter(age >= 18)

# Make variables into apropriate data type
data_selected <- data_selected %>%
  mutate(
    education = factor(education),
    race_simp = factor(race_simp),
    cit_simp = factor(cit_simp),
    income_personal = as.numeric(income_personal),
  ) %>%
  filter(!is.na(income_personal))

```

```{r}
# Break up income as categories (quartiles)
data_selected <- data_selected %>%
  mutate(
    income_cat = cut(
      income_personal,
      breaks = quantile(income_personal, probs = seq(0, 1, 0.25), na.rm = TRUE),
      include.lowest = TRUE
    )
  )
```

```{r}
# replicate weight column names
rep_weights <- paste0("pwgtp", 1:80)

# Build a SURVEY replicate design directly
des <- svrepdesign(
  weights = ~pwgtp,
  repweights = data_selected[, rep_weights],
  type = "successive-difference", 
  mse = TRUE,
  combined.weights = TRUE,
  data = data_selected
)

# CHI SQUARED TESTS

#Education x race
svy_edu_race <- svychisq(~education + race_simp, design = des, statistic = "Chisq")
svy_edu_race

#Citizenship x race
svy_cit_race <- svychisq(~cit_simp + race_simp,  design = des, statistic = "Chisq")
svy_cit_race

#Income x race
svy_inc_race <- svychisq(~income_cat + race_simp, design = des, statistic = "Chisq")
svy_inc_race

#Education x race
svy_edu_cit  <- svychisq(~education + cit_simp,   design = des, statistic = "Chisq")
svy_edu_cit
```

```{r}
#Bonferonni Function

############################################################
# Interpretation:
#   std_resid > 0  => observed count is higher than expected under independence
#   std_resid < 0  => observed count is lower than expected
#   |std_resid| > crit => "significant" cell after Bonferroni correction
############################################################

bonferroni_cells <- function(tab, alpha = 0.05) {
  chi <- suppressWarnings(chisq.test(tab))   # suppresses the approximation warning if it appears
  std_resid <- chi$stdres
  
  m <- length(std_resid)                    # number of cells tested
  crit <- qnorm(1 - alpha / (2 * m))        # two-sided Bonferroni critical value
  
  sig_idx <- which(abs(std_resid) > crit, arr.ind = TRUE)
  
  out <- list(
    chisq = chi,
    crit = crit,
    std_resid = std_resid,
    significant_cells = if (nrow(sig_idx) == 0) {
      tibble()
    } else {
      tibble(
        row_level = rownames(std_resid)[sig_idx[, 1]],
        col_level = colnames(std_resid)[sig_idx[, 2]],
        std_resid = std_resid[sig_idx]
      ) %>% arrange(desc(abs(std_resid)))
    }
  )
  return(out)
}
```

```{r}

# Education x Race
tab_edu_race <- table(data$education, data$race_simp)
bonf_edu_race <- bonferroni_cells(tab_edu_race, alpha = 0.05)

bonf_edu_race$crit
bonf_edu_race$significant_cells


```

```{r}

# Citizenship x Race
tab_cit_race <- table(data$cit, data$race_simp)
bonf_cit_race <- bonferroni_cells(tab_cit_race, alpha = 0.05)

bonf_cit_race$crit
bonf_cit_race$significant_cells
```

```{r}

# Income Category x Race
tab_inc_race <- table(data$income_cat, data$race_simp)
bonf_inc_race <- bonferroni_cells(tab_inc_race, alpha = 0.05)

bonf_inc_race$crit
bonf_inc_race$significant_cells
```


```{r}

# Education x Citizenship
tab_edu_cit <- table(data$education, data$cit)
bonf_edu_cit <- bonferroni_cells(tab_edu_cit, alpha = 0.05)

bonf_edu_cit$crit
bonf_edu_cit$significant_cells
```

